config/routes.rb
Rails.application.routes.draw do
  resources :locations 

  get 'regions/:id/locations' => 'locations#regional_location', defaults: { format: :json}
  
  resources :regions
  devise_for :users
  resources :boat_jobs
  resources :jobs 
  resources :boats
  resources :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
end

app/models/job.rb
class Job < ApplicationRecord
	has_many :boat_jobs
	has_many :boats, through: :boat_jobs
	has_many :locations, through: :regions
	belongs_to :origin, class_name: 'Location'
	belongs_to :destination, class_name: 'Location'

	validates :jname, presence: true 
	validates :description, presence: true 
	validates :origin, presence: true 
	validates :destination, presence: true 
	validates :containers, presence: true 
	validates :cost, presence: true 

	validates :jname, uniqueness: true

	validates :cost, numericality: true
	validates :cost, numericality: {greater_than_or_equal_to: 1000}

	validates_length_of :description, :minimum => 50

	before_destroy :removefk
	private
	def removefk
		boat_jobs.destroy_all
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = current_user.boats.reduce([]){|arr,boat| arr + boat.jobs }
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    Job.transaction do
      @job = Job.create(job_params)
      BoatJob.create!( job_id: @job.id, boat_id: params[:job][:boat_id])
    end
    respond_to do |format|
      if @job.id
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:description, :origin, :location, :destination, :containers, :cost)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form4">

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :job_description %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.select( :region_id, options_for_select(Region.pluck(:name,:id)), {prompt: 'Select a Region'}, {id: 'region_selector'}  )%>
  </div>

  <div class="field">
    <%= form.label :boat_id %>
    <%= form.select( :boat_id, options_for_select(current_user.boats.pluck(:bname,:id)) ) %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.select( :location_id, options_for_select(Location.pluck(:location_name,:id)), {prompt: 'Select an Origin'}, id: 'location_selector'  )%>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.select( :location_id, options_for_select(Location.pluck(:location_name,:id)), {prompt: 'Select a Destination'}, id: 'location_selector' ) %>
  </div>

  <div class="field">
    <%= form.label 'Container(s)' %>
    <%= form.number_field :containers, id: :job_container %>
  </div>



  <div class="field">
    <%= form.label :cost %>
    <%= form.number_field :cost, id: :job_cost %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script type="text/javascript">
  document.querySelector("#region_selector").addEventListener("change",function(event){
    let location_selects = document.querySelectorAll("#location_selector");
    console.log(event);
    axios.get(`/regions/${event.target.value}/locations`).then(function(response){
      console.log(response.data[0])
      //for each location select
      location_selects.forEach( locationSelect => {
        //wipe out existing options from select
        locationSelect.innerHTML = "";
        // re-add the options to the select
        response.data.forEach( location => {
          locationSelect.innerHTML += `<option value="${location.id}">${location.location_name}</option>`;
        });
      });
    });
  });

</script>


</div>

app/views/jobs/_jobs.html.erb
<!-- Partial to show jobs pertaining to that boat -->

<% @boat.jobs.each do |job| %>
	<li>Job Description: <%= job.description %></li>
	<li>Job Cost: <%= job.cost %></li>
	<li>Required Job Containers: <%= job.containers %></li>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Container(s)</th>
      <th>Cost</th>
      <th>Boat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.description %></td>
        <td><%= job.origin %></td>
        <td><%= job.destination %></td>
        <td><%= job.containers %></td>
        <td><%= job.cost %></td>
        <td><%= job.boats.map{|boat| boat.bname}.join(', ') %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Company Page', users_path %>

<%= link_to 'New Job', new_job_path %>
>>>>>>> 6266a28b98006a98efda88ef538d4630114375c6

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @job.origin %>
</p>


<p>
  <strong>Destination:</strong>
  <%= @job.destination %>
</p>

<p>
  <strong>Container(s):</strong>
  <%= @job.containers %>
</p>

<p>
<% @job.boats.each do |boat| %>
  <strong>Boat:</strong>
  <%= boat.bname %>
    <li><%= boat.bname %></li>
<% end %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @job.cost %>
</p>


<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>