config/routes.rb
Rails.application.routes.draw do
  resources :locations 

  get 'regions/:id/locations' => 'locations#regional_location', defaults: { format: :json}
  
  resources :regions
  devise_for :users
  resources :boat_jobs
  resources :jobs 
  resources :boats
  resources :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
end

app/models/boat_job.rb
class BoatJob < ApplicationRecord
  belongs_to :job
  belongs_to :boat
end

app/controllers/boat_jobs_controller.rb
class BoatJobsController < ApplicationController
  before_action :set_boat_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /boat_jobs
  # GET /boat_jobs.json
  def index
    @boat_jobs = BoatJob.all
  end

  # GET /boat_jobs/1
  # GET /boat_jobs/1.json
  def show
  end

  # GET /boat_jobs/new
  def new
    @boat_job = BoatJob.new
  end

  # GET /boat_jobs/1/edit
  def edit
  end

  # POST /boat_jobs
  # POST /boat_jobs.json
  def create
    @boat_job = BoatJob.new(boat_job_params)

    respond_to do |format|
      if @boat_job.save
        format.html { redirect_to @boat_job, notice: 'Boat job was successfully created.' }
        format.json { render :show, status: :created, location: @boat_job }
      else
        format.html { render :new }
        format.json { render json: @boat_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boat_jobs/1
  # PATCH/PUT /boat_jobs/1.json
  def update
    respond_to do |format|
      if @boat_job.update(boat_job_params)
        format.html { redirect_to @boat_job, notice: 'Boat job was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat_job }
      else
        format.html { render :edit }
        format.json { render json: @boat_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boat_jobs/1
  # DELETE /boat_jobs/1.json
  def destroy
    @boat_job.destroy
    respond_to do |format|
      format.html { redirect_to boat_jobs_url, notice: 'Boat job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boat_job
      @boat_job = BoatJob.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boat_job_params
      params.require(:boat_job).permit(:jobs_id, :boats_id)
    end
end

app/helpers/boat_jobs_helper.rb
module BoatJobsHelper
end

app/views/boat_jobs/_form.html.erb
<%= form_with(model: boat_job, local: true) do |form| %>
  <% if boat_job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(boat_job.errors.count, "error") %> prohibited this boat_job from being saved:</h2>

      <ul>
      <% boat_job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :jobs_id %>
    <%= form.text_field :jobs_id, id: :boat_job_jobs_id %>
  </div>

  <div class="field">
    <%= form.label :boats_id %>
    <%= form.text_field :boats_id, id: :boat_job_boats_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boat_jobs/edit.html.erb
<h1>Editing Boat Job</h1>

<%= render 'form', boat_job: @boat_job %>

<%= link_to 'Show', @boat_job %> |
<%= link_to 'Back', boat_jobs_path %>

app/views/boat_jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boat Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Jobs</th>
      <th>Boats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boat_jobs.each do |boat_job| %>
      <tr>
        <td><%= boat_job.jobs %></td>
        <td><%= boat_job.boats %></td>
        <td><%= link_to 'Show', boat_job %></td>
        <td><%= link_to 'Edit', edit_boat_job_path(boat_job) %></td>
        <td><%= link_to 'Destroy', boat_job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Boat Job', new_boat_job_path %>

app/views/boat_jobs/new.html.erb
<h1>New Boat Job</h1>

<%= render 'form', boat_job: @boat_job %>

<%= link_to 'Back', boat_jobs_path %>

app/views/boat_jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Jobs:</strong>
  <%= @boat_job.jobs %>
</p>

<p>
  <strong>Boats:</strong>
  <%= @boat_job.boats %>
</p>

<%= link_to 'Edit', edit_boat_job_path(@boat_job) %> |
<%= link_to 'Back', boat_jobs_path %>