config/routes.rb
Rails.application.routes.draw do
  resources :locations 

  get 'regions/:id/locations' => 'locations#regional_location', defaults: { format: :json}
  
  resources :regions
  devise_for :users
  resources :boat_jobs
  resources :jobs 
  resources :boats
  resources :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :user
  has_many :boat_jobs
  has_many :jobs, through: :boat_jobs
  belongs_to :region


  validates :bname, uniqueness: true

	has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
 	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :set_boat, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /boats
  # GET /boats.json
  def index
    @boats = current_user.boats
  end

  # GET /boats/1
  # GET /boats/1.json
  def show
  end

  # GET /boats/new
  def new
    @boat = Boat.new
  end

  # GET /boats/1/edit
  def edit
  end

  # POST /boats
  # POST /boats.json
  def create
    @boat = Boat.new(boat_params)
    @boat.user_id = current_user.id

    respond_to do |format|
      if @boat.save
        format.html { redirect_to @boat, notice: 'Boat was successfully created.' }
        format.json { render :show, status: :created, location: @boat }
      else
        format.html { render :new }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boats/1
  # PATCH/PUT /boats/1.json
  def update
    respond_to do |format|
      if @boat.update(boat_params)
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat }
      else
        format.html { render :edit }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @boat.destroy
    respond_to do |format|
      format.html { redirect_to boats_url, notice: 'Boat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boat
      @boat = Boat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boat_params
      params.require(:boat).permit(:bname, :capacity, :user_id, :photo, :region_id)
    end
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/views/boats/_form.html.erb
<%= form_with(model: boat, local: true) do |form| %>
  

  <% if boat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(boat.errors.count, "error") %> prohibited this boat from being saved:</h2>

      <ul>
      <% boat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="form3">

  <div class="field">
    <%= form.label 'Boat Name' %>
    <%= form.text_field :bname, id: :boat_bname %>
  </div>

  <div class="field">
    <%= form.label 'Capacity (of containers)' %>
    <%= form.number_field :capacity, id: :boat_capacity %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.select :region_id, options_for_select(Region.pluck(:name,:id) ), id: :boat_region %>
  </div>

  <div class="field">
    <%= form.label 'Boat Image' %>
    <%= form.file_field :photo, id: :boat_photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  
  </div
<% end %>

app/views/boats/edit.html.erb
<h1>Editing Boat</h1>

<%= render 'form', boat: @boat %>

<%= link_to 'Show', @boat %> |
<%= link_to 'Back', boats_path %>

app/views/boats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Boats</h1>

<table>
  <thead>
    <tr>
      <th>Boat</th>
      <th>Capacity (containers)</th>
      <th>Company Name</th>
      <th>Region</th>
      <th>Boat Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boats.each do |boat| %>
      <tr>
        <td><%= boat.bname %></td>
        <td><%= boat.capacity %></td>
        <td><%= boat.user.companyname %></td>
        <td><%= boat.region.name %></td>
        <td><%= image_tag boat.photo.url %></td>
        <td><%= link_to 'Show', boat %></td>
        <td><%= link_to 'Edit', edit_boat_path(boat) %></td>
        <td><%= link_to 'Destroy', boat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Boat', new_boat_path %>

app/views/boats/new.html.erb
<h1>New Boat</h1>

<%= render 'form', boat: @boat %>

<%= link_to 'Back', boats_path %>

app/views/boats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Boat Name:</strong>
  <%= @boat.bname %>
  <%= image_tag @boat.photo.url(:medium) %>
</p>

<p>
  <strong>Capacity (in containers):</strong>
  <%= @boat.capacity %>
</p>

<p>
	<strong>Region: </strong>
	<%= @boat.region.name %>
</p>

<% if @boat.jobs.any? %>
	<p>
		<strong>Jobs:</strong>
		<%= render partial: 'jobs/jobs' %>
	</p>
<% else %>
	<p>This Boat currently has no jobs</p>
	<%= link_to 'Click Here to Add a New Job', new_job_path %>
 <% end %>


<%= link_to 'Edit', edit_boat_path(@boat) %> |
<%= link_to 'Back', boats_path %>